"""Write current REAL_12M validation, manifest, and status artifacts."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = Path(os.getenv("SYNOPTIQ_ARTIFACTS_DIR", str(ROOT / "artifacts" / "real_12m"))).resolve()
MODEL_VERSION = os.getenv("SYNOPTIQ_MODEL_VERSION", "synoptiq-real-12m-20260929")
METRICS = ARTIFACTS / "metrics" / MODEL_VERSION


def main() -> None:
    metric_files = sorted(METRICS.glob("blend_eval_*.json"))
    metrics = [json.loads(path.read_text(encoding="utf-8")) for path in metric_files]
    skill_models = sorted((ARTIFACTS / "models" / "skill").glob("skillscore_*.joblib"))
    bust_models = sorted((ARTIFACTS / "models" / "bust").glob("bust_*.joblib"))
    calibration = sorted((ARTIFACTS / "calibration").glob("*.joblib"))
    inference_meta = json.loads((ARTIFACTS / "inference" / "metadata.json").read_text(encoding="utf-8"))
    training_run = json.loads((ARTIFACTS / "training_run.json").read_text(encoding="utf-8"))
    manifest_dir = ARTIFACTS / "manifests" / MODEL_VERSION
    manifest_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "data_mode": "real", "training_mode": "REAL_12M", "history_label": "FULL_HISTORY",
        "model_version": MODEL_VERSION, "synthetic_data_used": False,
        "forecast_sources": ["GFS", "IFS", "AIFS"], "truth_sources": ["IMERG", "ERA5"],
        "training_period": {"start": "2025-02-26", "end": "2026-02-25"},
        "validation_period": {"start": "2025-10-03", "end": "2025-11-25"},
        "test_period": {"start": "2025-11-26", "end": "2026-02-25"},
        "training_rows": training_run["forecast_rows"], "truth_rows": training_run["truth_rows"],
        "models": {"skill_regressors": len(skill_models), "bust_classifiers": len([p for p in bust_models if not p.name.startswith("bust_threshold")]), "total": 12},
        "calibration_artifacts": len(calibration), "inference_contexts": inference_meta["contexts"],
        "regions": ["kerala_western_ghats", "bay_of_bengal_east_coast", "indo_gangetic_plains"],
        "variables": ["precipitation", "temperature", "wind_speed"], "lead_hours": [24, 48, 72, 96, 120],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    (manifest_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (ARTIFACTS / "validation_report.json").write_text(json.dumps({"model_version": MODEL_VERSION, "metrics": metrics}, indent=2), encoding="utf-8")
    lines = [
        "# REAL_12M Validation Report", "", f"Model version: `{MODEL_VERSION}`", "",
        "Data period: `2025-02-26` through `2026-02-25`", "",
        "| Region | Variable | Test contexts | Blend metric | Best source | Relative improvement |",
        "|---|---:|---:|---:|---|---:|",
    ]
    for item in metrics:
        metric = "synoptiq_csi" if item["variable"] == "precipitation" else "synoptiq_rmse"
        best = "best_single_model_csi" if item["variable"] == "precipitation" else "best_single_model_rmse"
        improvement = "relative_csi_improvement_pct" if item["variable"] == "precipitation" else "relative_rmse_improvement_pct"
        lines.append(f"| {item['region']} | {item['variable']} | {item['n_test_contexts']} | {item[metric]} | {item['best_single_model']} ({item[best]}) | {item[improvement]}% |")
    lines += ["", f"Skill regressors: {len(skill_models)}", f"Bust classifiers: {len([p for p in bust_models if not p.name.startswith('bust_threshold')])}", f"Calibration artifacts: {len(calibration)}", f"Historical inference contexts: {inference_meta['contexts']}", "", "All reported metrics were generated by the existing chronological train/validation/test pipeline. Synthetic fallback: false."]
    (ARTIFACTS / "validation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    status = {
        "mode": "REAL_12M", "training_data": "PASS", "models": "PASS", "calibration": "PASS",
        "validation": "PASS", "historical_inference": "PASS", "backend": "DEGRADED",
        "frontend": "PASS", "live_forecast": "DEGRADED", "shap": "PASS", "synthetic_fallback": False,
        "model_version": MODEL_VERSION, "updated_at": datetime.now(timezone.utc).isoformat(),
        "known_limitations": ["Current live provider cycles are stale; explicit historical REAL_12M requests remain available."],
    }
    (ARTIFACTS / "status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    print(json.dumps({"manifest": str(manifest_dir / "manifest.json"), "metrics": len(metrics), "models": len(skill_models) + len([p for p in bust_models if not p.name.startswith("bust_threshold")]), "calibration": len(calibration)}, indent=2))


if __name__ == "__main__":
    main()
