/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ExtremesRouteImport } from './routes/extremes'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TrustAtlasRouteImport } from './routes/trust-atlas'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as WeightsRouteImport } from './routes/weights'
import { Route as ReplayEventIdRouteImport } from './routes/replay.$eventId'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtremesRoute = ExtremesRouteImport.update({
  id: '/extremes',
  path: '/extremes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustAtlasRoute = TrustAtlasRouteImport.update({
  id: '/trust-atlas',
  path: '/trust-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightsRoute = WeightsRouteImport.update({
  id: '/weights',
  path: '/weights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayEventIdRoute = ReplayEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => ReplayRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/extremes': typeof ExtremesRoute
  '/forecast': typeof ForecastRoute
  '/impact': typeof ImpactRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRouteWithChildren
  '/research': typeof ResearchRoute
  '/trust-atlas': typeof TrustAtlasRoute
  '/verification': typeof VerificationRoute
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/extremes': typeof ExtremesRoute
  '/forecast': typeof ForecastRoute
  '/impact': typeof ImpactRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRouteWithChildren
  '/research': typeof ResearchRoute
  '/trust-atlas': typeof TrustAtlasRoute
  '/verification': typeof VerificationRoute
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/extremes': typeof ExtremesRoute
  '/forecast': typeof ForecastRoute
  '/impact': typeof ImpactRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRouteWithChildren
  '/research': typeof ResearchRoute
  '/trust-atlas': typeof TrustAtlasRoute
  '/verification': typeof VerificationRoute
  '/weights': typeof WeightsRoute
  '/replay/$eventId': typeof ReplayEventIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/extremes'
    | '/forecast'
    | '/impact'
    | '/operations'
    | '/replay'
    | '/research'
    | '/trust-atlas'
    | '/verification'
    | '/weights'
    | '/replay/$eventId'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/extremes'
    | '/forecast'
    | '/impact'
    | '/operations'
    | '/replay'
    | '/research'
    | '/trust-atlas'
    | '/verification'
    | '/weights'
    | '/replay/$eventId'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/extremes'
    | '/forecast'
    | '/impact'
    | '/operations'
    | '/replay'
    | '/research'
    | '/trust-atlas'
    | '/verification'
    | '/weights'
    | '/replay/$eventId'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ExtremesRoute: typeof ExtremesRoute
  ForecastRoute: typeof ForecastRoute
  ImpactRoute: typeof ImpactRoute
  OperationsRoute: typeof OperationsRoute
  ReplayRoute: typeof ReplayRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  TrustAtlasRoute: typeof TrustAtlasRoute
  VerificationRoute: typeof VerificationRoute
  WeightsRoute: typeof WeightsRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extremes': {
      id: '/extremes'
      path: '/extremes'
      fullPath: '/extremes'
      preLoaderRoute: typeof ExtremesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-atlas': {
      id: '/trust-atlas'
      path: '/trust-atlas'
      fullPath: '/trust-atlas'
      preLoaderRoute: typeof TrustAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weights': {
      id: '/weights'
      path: '/weights'
      fullPath: '/weights'
      preLoaderRoute: typeof WeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$eventId': {
      id: '/replay/$eventId'
      path: '/$eventId'
      fullPath: '/replay/$eventId'
      preLoaderRoute: typeof ReplayEventIdRouteImport
      parentRoute: typeof ReplayRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReplayRouteChildren {
  ReplayEventIdRoute: typeof ReplayEventIdRoute
}

const ReplayRouteChildren: ReplayRouteChildren = {
  ReplayEventIdRoute: ReplayEventIdRoute,
}

const ReplayRouteWithChildren =
  ReplayRoute._addFileChildren(ReplayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ExtremesRoute: ExtremesRoute,
  ForecastRoute: ForecastRoute,
  ImpactRoute: ImpactRoute,
  OperationsRoute: OperationsRoute,
  ReplayRoute: ReplayRouteWithChildren,
  ResearchRoute: ResearchRoute,
  TrustAtlasRoute: TrustAtlasRoute,
  VerificationRoute: VerificationRoute,
  WeightsRoute: WeightsRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
